name: Discovery Manual PROD

on:
  workflow_dispatch:
    inputs:
      clusters: { description: "Comma-separated clusters", required: true, default: "Trades" }
      limit:    { description: "Row limit", required: true, default: "5" }
      langs:    { description: "Comma-separated language codes", required: true, default: "en" }

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AIRTABLE_TOKEN:      ${{ secrets.AIRTABLE_TOKEN }}
      AIRTABLE_API_KEY:    ${{ secrets.AIRTABLE_API_KEY }}
      AIRTABLE_BASE_ID:    ${{ secrets.AIRTABLE_BASE_ID }}
      AIRTABLE_TABLE_ID:   ${{ secrets.AIRTABLE_TABLE_ID }}
      AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Generate CSV (mock; replace with real discovery later)
        env:
          CLUSTERS: ${{ github.event.inputs.clusters }}
          LIMIT:    ${{ github.event.inputs.limit }}
          LANGS:    ${{ github.event.inputs.langs }}
        run: |
          python scripts/run_discovery.py --clusters "$CLUSTERS" --limit "$LIMIT" --langs "$LANGS" --out data/candidates_raw.csv

      - name: Show CSV
        run: |
          echo "linecount:"; wc -l data/candidates_raw.csv
          echo "preview:"; head -n 5 data/candidates_raw.csv

      - name: Syntax check uploader
        run: python -m py_compile scripts/upload_csv_field_aware.py

      - name: Upload CSV (field-aware; respects single-select options)
        run: python scripts/upload_csv_field_aware.py
