name: discovery

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pandas SPARQLWrapper rapidfuzz Metaphone requests

      - name: Show SPARQL template header (sanity)
        run: |
          echo "Template first 20 lines:"
          sed -n '1,20p' queries/query_template.sparql

      - name: Run discovery (OPEN mode, safe filters)
        run: |
          set -e
          mkdir -p data
          echo "Running discovery in OPEN mode with safe surname filters…"
          python scripts/wikidata_nomen_agent.py \
            --mode open \
            --clusters Trades Agriculture \
            --limit 80 \
            --langs "en,de,fr,es,it" \
            --outfile data/candidates_raw.csv

      - name: Debug output (if any)
        if: ${{ always() }}
        run: |
          echo "Data dir contents:"; ls -l data || true
          echo "CSV line count:";    wc -l data/candidates_raw.csv || true
          echo "First 5 lines:";     head -n 5 data/candidates_raw.csv || true

      - name: Upload to Airtable (only if CSV exists)
        if: ${{ hashFiles('data/candidates_raw.csv') != '' }}
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
        run: |
          python scripts/push_to_airtable.py --csv data/candidates_raw.csv

      - name: No CSV produced
        if: ${{ hashFiles('data/candidates_raw.csv') == '' }}
        run: echo "No CSV produced; confirm template shows {SURNAME_FILTER}/{OCCUPATION_FILTER} and logs show [FILTER] ... (not REGEX...)."
