name: discovery
on:
  workflow_dispatch:    # allows manual runs
  schedule:
    - cron: "0 9 * * 1" # (optional) Mondays 09:00 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas SPARQLWrapper rapidfuzz Metaphone requests

      - name: Make data folder
        run: mkdir -p data

      - name: Run discovery
        run: |
          python scripts/wikidata_nomen_agent.py \
            --clusters Medicine Law Arts \
            --limit 400 \
            --outfile data/candidates_raw.csv
      - name: Upload to Airtable
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
        run: |
          python scripts/push_to_airtable.py --csv data/candidates_raw.csv
