name: Discovery (Manual)

on:
  workflow_dispatch:
    inputs:
      clusters:
        description: "Space-separated clusters (e.g. 'Trades Arts')"
        required: true
        default: "Arts"
      limit:
        description: "Max results per occupation query"
        required: true
        default: "60"
      langs:
        description: "Languages for labels (comma-separated, e.g. en,de,fr)"
        required: true
        default: "en,de,fr"
      mode:
        description: "open (surname filter only) or strict (adds occupation filter)"
        required: true
        default: "strict"

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Dispatch inputs => clusters=${{ inputs.clusters }}, limit=${{ inputs.limit }}, langs=${{ inputs.langs }}, mode=${{ inputs.mode }}"
