name: Harvest + Enrich + Analyze (Web)

on:
  workflow_dispatch:
    inputs:
      wikidata_limit_per_prof:
        description: "Max people per profession (default 40)"
        required: true
        default: "40"
      professions:
        description: "Comma-separated profession labels (leave blank to use default list)"
        required: false
        default: ""
      threshold:
        description: "Min PMI score gap to write (e.g., 0.7)"
        required: true
        default: "0.7"
      dry_run:
        description: "Don't write predictions (true/false)"
        required: true
        default: "true"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AIRTABLE_TOKEN:      ${{ secrets.AIRTABLE_TOKEN }}
      AIRTABLE_API_KEY:    ${{ secrets.AIRTABLE_API_KEY }}
      AIRTABLE_BASE_ID:    ${{ secrets.AIRTABLE_BASE_ID }}
      AIRTABLE_TABLE_ID:   ${{ secrets.AIRTABLE_TABLE_ID }}
      AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
      WIKIDATA_LIMIT_PER_PROF: ${{ github.event.inputs.wikidata_limit_per_prof }}
      WIKIDATA_PROF_LIST:      ${{ github.event.inputs.professions }}
      THRESHOLD:           ${{ github.event.inputs.threshold }}
      DRY_RUN:             ${{ github.event.inputs.dry_run }}
      FORCE_LABEL:         profession
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: python -m pip install --upgrade pip requests

      - name: Harvest from Wikidata
        run: |
          echo "::group::Harvester inputs"
          echo "professions=${WIKIDATA_PROF_LIST:-<default list>}"
          echo "limit_per_prof=${WIKIDATA_LIMIT_PER_PROF}"
          echo "::endgroup::"
          # run unbuffered so prints show immediately
          python -u scripts/fetch_wikidata_people.py

      - name: Enrich etymology (meaning/roots)
        run: python -u scripts/enrich_etymology.py

      - name: Score etymology vs profession
        run: python -u scripts/score_etymology_to_profession.py

      - name: Analyze names statistically (PMI)
        run: python -u scripts/analyze_name_profession.py
