name: Discovery (Manual — PROD)

on:
  workflow_dispatch:
    inputs:
      clusters: { description: "Clusters (e.g., Trades)", default: "Trades" }
      limit:    { description: "Row limit", default: "40" }
      langs:    { description: "Label languages", default: "en" }
      mode:     { description: "open or strict", default: "open" }

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install SPARQLWrapper requests

      - name: Preflight (show files)
        run: |
          echo "== query template head =="; sed -n '1,60p' queries/query_template.sparql || true
          echo "== clusters JSON head =="; sed -n '1,120p' dictionaries/occupations_by_cluster.json || true

      - name: Orchestrate discovery → CSV → Airtable
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }} # set to table ID
        run: |
          python scripts/orchestrate_nomen.py \
            --clusters "${{ github.event.inputs.clusters }}" \
            --limit "${{ github.event.inputs.limit }}" \
            --langs "${{ github.event.inputs.langs }}" \
            --mode "${{ github.event.inputs.mode }}"
