name: Secrets Check
on: { workflow_dispatch: {} }

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      AIRTABLE_TABLE_ID: ${{ secrets.AIRTABLE_TABLE_ID }}
      AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
    steps:
      - name: Show which secrets are present
        run: |
          echo "AIRTABLE_TOKEN:      $([ -n \"$AIRTABLE_TOKEN\" ] && echo YES || echo NO)"
          echo "AIRTABLE_API_KEY:    $([ -n \"$AIRTABLE_API_KEY\" ] && echo YES || echo NO)"
          echo "AIRTABLE_BASE_ID:    ${AIRTABLE_BASE_ID:-NO}"
          echo "AIRTABLE_TABLE_ID:   ${AIRTABLE_TABLE_ID:-NO}"
          echo "AIRTABLE_TABLE_NAME: ${AIRTABLE_TABLE_NAME:-NO}"
          # Fail if neither token secret is set
          if [ -z "$AIRTABLE_TOKEN" ] && [ -z "$AIRTABLE_API_KEY" ]; then
            echo "No token found (need AIRTABLE_TOKEN or AIRTABLE_API_KEY)."; exit 1; fi
          # Fail if neither table id nor table name is set
          if [ -z "$AIRTABLE_TABLE_ID" ] && [ -z "$AIRTABLE_TABLE_NAME" ]; then
            echo "No table set (need AIRTABLE_TABLE_ID or AIRTABLE_TABLE_NAME)."; exit 1; fi
